variables:
  #Project Options
  build: 'maven'
  vmImage: 'ubuntu-latest'
  pkgFeed: 'Playground/java-demo'
  buildArtifactName: 'drop'
  jdkVersion: 11
  
  #Maven options
  mvnTestOptions: '-DruntimeProduct=MULE'
  mvnCompileOptions: '-DruntimeProduct=MULE'
  mvnPkgOptions: '-DruntimeProduct=MULE'
  buildToPublish: '**/*'
  packageToPublish: '**/*.jar'
  mvnTestResultsFiles: '**/TEST-*.xml'
  
  #Fortify options
  fortifyAppName: 'java-test'
  fortifyAppVersion: '1.1'
  fortifyBuildId: $(Build.BuildId)
  fortifySourceVersion: '8'
  
    
trigger:
- master

resources:
  repositories:
  - repository: templates
    name: "Playground/pattern-library"
    type: git
    ref: rev

stages:
- stage: buildApplication
  displayName: 'Build Application'
  jobs:
  - job: build
    displayName: 'Build'
    pool:
      vmImage: $(vmImage)
    steps:
    - template: /templates/java-maven/step-init.yml@templates
      parameters:
        pkgFeed: $(pkgFeed)
        jdkVersion: 11
    - template: /templates/java-maven/step-compile.yml@templates
      parameters:
        jdkVersion: $(jdkVersion)
        options: $(mvnCompileOptions)
    - template: /templates/generic/step-publish-pipeline-artifact.yml@templates          
      parameters:
        toPublish: $(buildToPublish)
        artifactName: $(buildArtifactName)
  - job: quality
    displayName: 'Quality'
    pool:
      vmImage: $(vmImage)
    dependsOn: build
    condition: succeeded()
    steps:
    - template: /templates/generic/step-download-pipeline-artifact.yml@templates
      parameters:
        buildArtifactName: $(buildArtifactName)
    - template: /templates/java-maven/step-init.yml@templates
      parameters:
        pkgFeed: $(pkgFeed)
        jdkVersion: $(jdkVersion)
    - template: /templates/java-maven/step-ut.yml@templates
      parameters:
        jdkVersion: $(jdkVersion)
        options: $(mvnTestOptions)
        testResultsFiles: $(mvnTestResultsFiles)
        testRunTitle: ''
    - template: /templates/generic/step-quality-sonar.yml@templates
  - job: security
    displayName: 'Security'
    pool: 'DevSecOps Agent Pool'
    dependsOn: build
    condition: succeeded()
    steps:
    - template: /templates/generic/step-download-pipeline-artifact.yml@templates
      parameters:
        buildArtifactName: $(buildArtifactName)
    - template: /templates/generic/step-sca-whitesource.yml@templates
      parameters:
        pkgFeed: $(pkgFeed)
        args: ''
    - template: /templates/generic/step-sast-fortify.yml@templates
      parameters:
        buildId: $(fortifyBuildId)
        applicationType: 'java'
        customRules: ''
        scanParams: ''
        buildAnalyzerParams: ''
        classPath: ''
        sourceVersion: $(fortifySourceVersion)
        sourcePath: ''
        buildOptions: ''
        sourceTranslate: ''
        otherTranslate: ''
        appName: $(fortifyAppName)
        appVersion: $(fortifyAppVersion)
        sscProxyUrl: ''
        sscProxyUser: ''
        sscProxyPass: ''
  - job: package
    displayName: 'Package'
    pool:
      vmImage: $(vmImage)
    dependsOn:
    - quality
    - security
    condition: succeeded()
    steps:
    - template: /templates/generic/step-download-pipeline-artifact.yml@templates
      parameters:
        buildArtifactName: $(buildArtifactName)
    - template: /templates/java-maven/step-init.yml@templates
      parameters:
        pkgFeed: $(pkgFeed)
        jdkVersion: $(jdkVersion)
    - template: /templates/java-maven/step-package.yml@templates
      parameters:
        jdkVersion: $(jdkVersion)
        options: $(mvnPkgOptions)
    - template: /templates/generic/step-publish-pipeline-artifact.yml@templates          
      parameters:
        toPublish: $(packageToPublish)
        artifactName: 'package'

- stage: deployApplication
  displayName: 'Deploy Application'
  dependsOn: buildApplication
  jobs:
  - job: deploy
    displayName: 'Deploy'
    steps:
    - template: /templates/generic/step-download-pipeline-artifact.yml@templates
- stage: verifyApplication
  displayName: 'Verify Application'
  dependsOn: deployApplication
  jobs:
  - job: security
    displayName: 'Security'
    steps:
    - template: /templates/generic/step-dast-webinspect.yml@templates
  - job: functionalTest
    displayName: 'Functional Test'
    steps:
    - template: /templates/generic/step-ft-tosca.yml@templates
