#%RAML 1.0
title: QBE_Test_Application
baseUri: http://apilayer.net/api/
securitySchemes:
  basic:
    type: Basic Authentication
    displayName: Basic Authentication
protocols: [HTTP]
types:
  apiresponse:
    properties:
      valid: boolean
      number: string
      local_format: string
      international_format: string
      country_prefix: string
      country_code: string
      country_name: string
      location: string
      carrier: string
      line_type: string

/validate:
  get:
    queryParameters:
      access_key: string
      number: string
      country_code: string
      format: string
    displayName: phone number validate
    responses:
      200:
        body:
            application/json:
                type: apiresponse
                example:
                  {
                  "valid": true,
                  "number": "610414225354",
                  "local_format": "0414225354",
                  "international_format": "+61414225354",
                  "country_prefix": "+61",
                  "country_code": "AU",
                  "country_name": "Australia",
                  "location": "",
                  "carrier": "Vodafone Hutchison Australia Pty Ltd (VHA)",
                  "line_type": "mobile"
                  }

